// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RabbitMQConsumer2.Models;

public partial class RabbitMq
{
    public int Id { get; set; }

    public Guid Guid { get; set; }

    public string Queue { get; set; }

    public string Message { get; set; }

    public string Exchange { get; set; }

    public string ConsumerName { get; set; }
}