// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace AzureBusServiceConsumer1.Models
{
    public partial class AzureBusServiceContext : DbContext
    {
        public AzureBusServiceContext()
        {
        }

        public AzureBusServiceContext(DbContextOptions<AzureBusServiceContext> options)
            : base(options)
        {
        }

        public virtual DbSet<AzureBus> AzureBusService { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseSqlServer("Data Source=VID-DT-1051;Initial Catalog=SoftechWorldWide;Trust Server Certificate=True;Integrated Security=True");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<AzureBus>(entity =>
            {
                entity.Property(e => e.ConsumerName)
                    .IsRequired()
                    .HasDefaultValueSql("(N'')");

                entity.Property(e => e.Message).IsRequired();

                entity.Property(e => e.Topic).IsRequired();
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}